version: 2.1

jobs:
  build-gradle:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "app/build.gradle.kts" }}
            - gradle-cache-v1-
      - run:
          name: build
          command: |
            cd app
            ./gradlew :task:fatjar
            ./gradlew :web:fatjar
      - persist_to_workspace:
          root: app
          paths:
            - web/build/libs/web-1.0-all.jar
            - task/build/libs/task-1.0-all.jar

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-v1-{{ checksum "app/build.gradle.kts" }}
  build-docker:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: app
      - run:
          name: test
          command: |
            ls -la
            ls -la app/web/build/libs/web-1.0-all.jar
            ls -la app/task/build/libs/task-1.0-all.jar
      
workflows:
  version: 2
  workflow:
    jobs:
      - build-gradle:
          filters:
            branches:
              only: master
      - build-docker:
          requires:
            - build-gradle
