version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "app/build.gradle.kts" }}
            - gradle-cache-v1-
      - run:
          name: build
          command: |
            cd app
            ./gradlew :task:fatjar
            ./gradlew :web:fatjar
      - persist_to_workspace:
          root: app
          paths:
            - web/build/libs/web-1.0-all.jar
            - task/build/libs/task-1.0-all.jar

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-v1-{{ checksum "app/build.gradle.kts" }}
      
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - slack/status:
          requires:
            - build
