version: 2.1

jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk11:jdk-11.0.7_10-alpine
    steps:
      - chechout
      - restore_cache:
          keys:
            - toot-counter-gradle-cache-v1
      - run:
          name: build
          command: |
            cd app
            ./gradlew :task:fatjar
            ./gradlew :web:fatjar

      - save_cache:
          path:
            - ~/.gradle
          keys: toot-counter-gradle-cache-v1
      
workflows:
  version: 2
  ci:
    filters:
      branches:
        only:
          - master
    jobs:
      - build