version: 2.1

jobs:
  build-gradle:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-v1-{{ checksum "app/build.gradle.kts" }}
            - gradle-cache-v1-
      - run:
          name: build
          command: |
            cd app
            ./gradlew :task:fatjar
            ./gradlew :web:fatjar
      - persist_to_workspace:
          root: app
          paths:
            - web/build/libs/web-1.0-all.jar
            - task/build/libs/task-1.0-all.jar

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-v1-{{ checksum "app/build.gradle.kts" }}
  build-docker:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - attach_workspace:
          at: app
      - add_ssh_keys:
          fingerprints:
            - "76:4d:4b:8c:c5:61:ad:c5:d3:9e:b5:e5:67:2c:e6:97"
      - run:
          name: prepare ssh
          command: ssh-keyscan -H $DEPLOY_HOST_NAME >> ~/.ssh/known_hosts
      - run:
          name: test
          command: ssh $DEPLOY_USER_NAME@$DEPLOY_HOST_NAME whoami
            
            
      
workflows:
  version: 2
  workflow:
    jobs:
      - build-gradle:
          filters:
            branches:
              only: master
      - build-docker:
          requires:
            - build-gradle
