FROM adoptopenjdk/openjdk11:jdk-11.0.7_10-alpine as build-env
ADD . /app
WORKDIR /app
RUN ./gradlew :task:fatJar

FROM adoptopenjdk/openjdk11:jdk-11.0.7_10-alpine
COPY --from=build-env /app/web/build/libs/task-1.0-all.jar /opt/task.jar
WORKDIR /opt

CMD [ "java", "-jar", "task.jar"]