name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test
      env: 
        TOOT_COUNTER_DB_JDBC_URL: ${{ secrets.TOOT_COUNTER_DB_JDBC_URL }}
      run: echo $TOOT_COUNTER_DB_JDBC_URL
