name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ssh config
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOST: ${{ secrets.SSH_KNOWN_HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        echo "$SSH_KNOWN_HOST" > known_hosts
        chmod 600 known_hosts
    
    - name: sync source
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_URL: ${{ secrets.SSH_URL }}
      run: |
        rsync -e "ssh -i private_key -o UserKnownHostsFile=known_hosts" -vr --delete --exclude=.git . "$SSH_USER"@"$SSH_URL":~/toot-counter/
        
