name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ssh config
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOST: ${{ secrets.SSH_KNOWN_HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        echo "$SSH_KNOWN_HOST" > known_hosts
        chmod 600 known_hosts
    
    - name: push source
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_URL: ${{ secrets.SSH_URL }}
        GIT_SSH_COMMAND: ssh -i private_key -o UserKnownHostsFile=known_hosts
      run: |
        git remote add prod "$SSH_USER"@"$SSH_URL":~/toot-counter
        git push prod master
        
